name: Publish package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Test code with coverage
        run: echo 'testing... xD'
        
      - name: Build
        run: yarn build

      - name: Publish on npm.js
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}